# Generated by Django 5.1.1 on 2024-09-22 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_tokenotpuser_token_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenotpuser',
            name='token_otp',
        ),
    ]
