# Generated by Django 5.1.1 on 2024-09-22 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_remove_tokenotpuser_token_otp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tokenotpuser',
            name='is_expired',
        ),
        migrations.RemoveField(
            model_name='tokenotpuser',
            name='is_used',
        ),
        migrations.CreateModel(
            name='TokenUserLog',
            fields=[
                ('itoken', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_used', models.BooleanField(default=False)),
                ('token_otp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.tokenotpuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
