# Generated by Django 5.1.1 on 2024-09-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_remove_tokenotpuser_is_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenuserlog',
            name='date_used',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tokenuserlog',
            name='token_otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
