# Generated by Django 5.1.1 on 2024-09-22 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_tokenuserlog_date_used_alter_tokenuserlog_token_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenuserlog',
            name='date_used',
            field=models.DateTimeField(null=True),
        ),
    ]
