# Generated by Django 5.1.1 on 2024-09-22 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_alter_tokenuserlog_date_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tokenuserlog',
            old_name='is_used',
            new_name='is_already_used',
        ),
    ]
