# Generated by Django 5.1.1 on 2024-09-23 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_rename_is_used_tokenuserlog_is_already_used'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenotpuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tokenuserlog',
            name='token_otp',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
